<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return view('Admin.home');
});
Route::get('/', 'ShopController@index');
Route::prefix('shop')->group(function (){
    Route::get('/contact',[
        'as'=>'contact',
        'uses'=>'ShopController@contact'
    ]);
    Route::get('/about',[
        'as'=>'about',
        'uses'=>'ShopController@about'
    ]);
    Route::post('/contactPost',[
        'as'=>'contact.post',
        'uses'=>'ShopController@contactPost'
    ]);
    Route::get('/partner',[
        'as'=>'partner',
        'uses'=>'ShopController@partner'
    ]);
    Route::get('/article',[
        'as'=>'article',
        'uses'=>'ShopController@article'
    ]);
    Route::get('/Article/{slug}/{id}',[
        'as'=>'article.detail',
        'uses'=>'ShopController@article_detail'
    ]);
    Route::get('/product',[
        'as'=>'product',
        'uses'=>'ShopController@product'
    ]);
    Route::get('/allProduct/{slug}/{id}',[
        'as'=>'all.product.by.category',
        'uses'=>'ShopController@allProductByCategory'
    ]);
    Route::get('/product_detail/{slug}/{id}',[
        'as'=>'product.detail',
        'uses'=>'ShopController@product_detail'
    ]);
});
Route::prefix('admin')->group(function (){
    Route::get('/adminLogin','AdminController@loginAdmin')->name('adminLogin');
    Route::post('/adminLogin','AdminController@postLoginAdmin');
    Route::get('/logout',[
        'as'=>'logout',
        'uses'=>'AdminController@logoutAdmin'
    ]);
    //User
    Route::prefix('user')->group(function () {
        Route::get('/list',[
            'as'=>'user.index',
            'uses'=>'UserController@index'
        ]);
        Route::get('/create',[
            'as'=>'user.create',
            'uses'=>'UserController@create'
        ]);
        Route::post('/store',[
            'as'=>'user.store',
            'uses'=>'UserController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'user.edit',
            'uses'=>'UserController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'user.delete',
            'uses'=>'UserController@delete'
        ]);
        Route::post('/update',[
            'as'=>'user.update',
            'uses'=>'UserController@update'
        ]);
    });
    //Abouts
    Route::prefix('about')->group(function () {
        Route::get('/list',[
            'as'=>'about.index',
            'uses'=>'AboutController@index'
        ]);
        Route::get('/create',[
            'as'=>'about.create',
            'uses'=>'AboutController@create'
        ]);
        Route::post('/store',[
            'as'=>'about.store',
            'uses'=>'AboutController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'about.edit',
            'uses'=>'AboutController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'about.delete',
            'uses'=>'AboutController@delete'
        ]);
        Route::post('/update',[
            'as'=>'about.update',
            'uses'=>'AboutController@update'
        ]);
    });
    //Articles
    Route::prefix('article')->group(function () {
        Route::get('/list',[
            'as'=>'article.index',
            'uses'=>'ArticleController@index'
        ]);
        Route::get('/create',[
            'as'=>'article.create',
            'uses'=>'ArticleController@create'
        ]);
        Route::post('/store',[
            'as'=>'article.store',
            'uses'=>'ArticleController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'article.edit',
            'uses'=>'ArticleController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'article.delete',
            'uses'=>'ArticleController@delete'
        ]);
        Route::post('/update',[
            'as'=>'article.update',
            'uses'=>'ArticleController@update'
        ]);
    });
    //Partner
    Route::prefix('partner')->group(function () {
        Route::get('/list',[
            'as'=>'partner.index',
            'uses'=>'PartnerController@index'
        ]);
        Route::get('/create',[
            'as'=>'partner.create',
            'uses'=>'PartnerController@create'
        ]);
        Route::post('/store',[
            'as'=>'partner.store',
            'uses'=>'PartnerController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'partner.edit',
            'uses'=>'PartnerController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'partner.delete',
            'uses'=>'PartnerController@delete'
        ]);
        Route::post('/update',[
            'as'=>'partner.update',
            'uses'=>'PartnerController@update'
        ]);
    });
    //Setting
    Route::prefix('setting')->group(function () {
        Route::get('/list',[
            'as'=>'setting.index',
            'uses'=>'SettingController@index'
        ]);
        Route::get('/create',[
            'as'=>'setting.create',
            'uses'=>'SettingController@create'
        ]);
        Route::post('/store',[
            'as'=>'setting.store',
            'uses'=>'SettingController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'setting.edit',
            'uses'=>'SettingController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'setting.delete',
            'uses'=>'SettingController@delete'
        ]);
        Route::post('/update',[
            'as'=>'setting.update',
            'uses'=>'SettingController@update'
        ]);
    });
    //Category
    Route::prefix('category')->group(function () {
        Route::get('/list',[
            'as'=>'category.index',
            'uses'=>'CategoryController@index'
        ]);
        Route::get('/create',[
            'as'=>'category.create',
            'uses'=>'CategoryController@create'
        ]);
        Route::post('/store',[
            'as'=>'category.store',
            'uses'=>'CategoryController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'category.edit',
            'uses'=>'CategoryController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'category.delete',
            'uses'=>'CategoryController@delete'
        ]);
        Route::post('/update',[
            'as'=>'category.update',
            'uses'=>'CategoryController@update'
        ]);
    });
    //Material
    Route::prefix('material')->group(function () {
        Route::get('/list',[
            'as'=>'material.index',
            'uses'=>'MaterialController@index'
        ]);
        Route::get('/create',[
            'as'=>'material.create',
            'uses'=>'MaterialController@create'
        ]);
        Route::post('/store',[
            'as'=>'material.store',
            'uses'=>'MaterialController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'material.edit',
            'uses'=>'MaterialController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'material.delete',
            'uses'=>'MaterialController@delete'
        ]);
        Route::post('/update',[
            'as'=>'material.update',
            'uses'=>'MaterialController@update'
        ]);
    });
    //Product
    Route::prefix('product')->group(function () {
        Route::get('/list',[
            'as'=>'product.index',
            'uses'=>'ProductController@index'
        ]);
        Route::get('/create',[
            'as'=>'product.create',
            'uses'=>'ProductController@create'
        ]);
        Route::post('/store',[
            'as'=>'product.store',
            'uses'=>'ProductController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'product.edit',
            'uses'=>'ProductController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'product.delete',
            'uses'=>'ProductController@delete'
        ]);
        Route::post('/update',[
            'as'=>'product.update',
            'uses'=>'ProductController@update'
        ]);
    });
    //Banner
    Route::prefix('banner')->group(function () {
        Route::get('/list',[
            'as'=>'banner.index',
            'uses'=>'BannerController@index'
        ]);
        Route::get('/create',[
            'as'=>'banner.create',
            'uses'=>'BannerController@create'
        ]);
        Route::post('/store',[
            'as'=>'banner.store',
            'uses'=>'BannerController@store'
        ]);
        Route::get('/edit/{id}',[
            'as'=>'banner.edit',
            'uses'=>'BannerController@edit'
        ]);
        Route::get('/delete/{id}',[
            'as'=>'banner.delete',
            'uses'=>'BannerController@delete'
        ]);
        Route::post('/update',[
            'as'=>'banner.update',
            'uses'=>'BannerController@update'
        ]);
    });
});

